Repository geoadmin/service-wmts, pull requests merged in 2022-08, with the labels that each got.

#41 New Release v1.1.0 - #minor
  Makefile
  README.md
  app/helpers/s3.py
  app/settings.py
  buildspec.yml
  docker-compose-ci.yml
  docker-compose.yml
  openapi.yml
  scripts/local-mapserver/inline_points.map
Labels: new-release

#43 BGDIINF_SB-2520: Updated logging utilities for better logging configuration
  .pylintrc
  Pipfile
  Pipfile.lock
  app/helpers/wmts_config.py
  config/logging-cfg-local.yml
Labels: feature

#44 New Release v1.1.1 - #patch
  .pylintrc
  Pipfile
  Pipfile.lock
  app/helpers/wmts_config.py
  config/logging-cfg-local.yml
Labels: new-release

#45 minio volume should be mounted/created with current user
  docker-compose.yml
Labels: feature

#46 BGDIINF_SB-2520: Updated logging library
  Pipfile
  Pipfile.lock
  config/logging-cfg-local.yml
Labels: feature

#47 New Release v1.1.2 - #patch
  Pipfile
  Pipfile.lock
  config/logging-cfg-local.yml
  docker-compose.yml
Labels: new-release

#48 Revert "minio volume should be mounted/created with current user"
  docker-compose.yml
Labels: feature

#49 BGDIINF_SB-2561: Changed the readiness probe to match our API guideline
  Makefile
  app/helpers/wms.py
  app/routes.py
  app/settings.py
  minio.env
  openapi.yml
  tests/unit_tests/test_checker.py
Labels: feature

#50 New Release v1.2.0 - #minor
  Makefile
  app/helpers/wms.py
  app/routes.py
  app/settings.py
  docker-compose.yml
  minio.env
  openapi.yml
  tests/unit_tests/test_checker.py
Labels: new-release

#51 BGDIINF_SB-2561: Added curl required for health check on vhost setup
  Dockerfile
Labels: bug

#52 New Release v1.2.1 - #patch
  Dockerfile
Labels: new-release
