Repository geoadmin/service-wmts, pull requests merged in 2023-02, with the labels that each got.

#63 BGDIINF_SB-2765: configure keep-alive in socket
  app/helpers/s3.py
  tests/unit_tests/test_get_tile.py
Labels: feature

#64 New Release v1.5.0 - #minor
  app/helpers/s3.py
  tests/unit_tests/test_get_tile.py
Labels: new-release

#65 BGDIINF_SB-2765: allow changing of socket options with http.client - #minor
  app/helpers/s3.py
Labels: bug

#68 BGDIINF_SB-2800: rm buildspec as being held in repo infra-terraform-bgdi-builder
  buildspec.yml
Labels: feature
